FROM golang:1.26.4-alpine3.23 AS builder

RUN apk add --no-cache make gcc musl-dev linux-headers git bash build-base libc-dev libstdc++

ADD . /go-ethereum
RUN cd /go-ethereum && make faucet

# Pull faucet into a second stage deploy alpine container
FROM alpine:3.23.3

RUN apk add --no-cache ca-certificates curl jq tini
COPY --from=builder /go-ethereum/build/bin/faucet /usr/local/bin/
COPY --from=builder /go-ethereum/.env.faucet /.env

WORKDIR /
EXPOSE 8080
ENTRYPOINT ["faucet"]