FROM golang:1.16-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git bash

ADD . /go-ethereum
RUN cd /go-ethereum && make faucet

# Pull Geth into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates curl jq tini
COPY --from=builder /go-ethereum/build/bin/faucet /usr/local/bin/
COPY --from=builder /go-ethereum/.env.faucet /.env

WORKDIR /
EXPOSE 8080
ENTRYPOINT ["faucet"]